trigger_job:
  trigger:
    project: abstract-germany/community-theme/community-theme-tutor
    branch: community-theme.palm
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always
